# Generated by Django 5.2.5 on 2025-10-07 14:05

import apps.invites.models
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_deleted_at_organization_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverInvite',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Administrative Staff', 'Administrative Staff'), ('Surgeon', 'Surgeon'), ('Physician', 'Physician'), ('Dentist', 'Dentist'), ('Optometrist', 'Optometrist'), ('Radiologist', 'Radiologist'), ('Psychiatrist', 'Psychiatrist'), ('Physical Therapist', 'Physical Therapist'), ('Occupational Therapist', 'Occupational Therapist'), ('Medical Lab Technician', 'Medical Lab Technician'), ('Paramedic', 'Paramedic'), ('Dietitian', 'Dietitian'), ('Speech Therapist', 'Speech Therapist'), ('Medical Assistant', 'Medical Assistant'), ('Respiratory Therapist', 'Respiratory Therapist'), ('Midwife', 'Midwife'), ('Orthopedist', 'Orthopedist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist'), ('Oncologist', 'Oncologist'), ('Endocrinologist', 'Endocrinologist'), ('Anesthesiologist', 'Anesthesiologist')], max_length=40)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.invites.models.default_expires_at)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('resend_count', models.PositiveIntegerField(default=0, help_text='Number of times the invitation was resent.')),
                ('invited_by', models.ForeignKey(blank=True, help_text='The user who sent this invitation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_caregiver_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_invites', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Caregiver Invitation',
                'verbose_name_plural': 'Caregiver Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='invites_car_token_ce0d09_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('organization'), name='unique_invite_per_org')],
            },
        ),
    ]
