# Generated by Django 5.2.5 on 2025-09-02 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pkid', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Caregiver', 'Caregiver'), ('Organization', 'Organization'), ('Organization_Admin', 'Organization_Admin')], db_index=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_invited', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'deleted_at'], name='accounts_us_email_52ce49_idx'), models.Index(fields=['email', 'is_active', 'is_deleted'], name='accounts_us_email_6ba883_idx'), models.Index(fields=['is_verified', 'is_active', 'is_deleted'], name='accounts_us_is_veri_afbff0_idx'), models.Index(fields=['role', 'is_active', 'is_deleted'], name='accounts_us_role_a0a83e_idx'), models.Index(fields=['deleted_at'], name='accounts_us_deleted_08a5c0_idx')],
            },
        ),
    ]
