
from shared.text_choices import CaregiverTypes

role_abbreviation = {
    CaregiverTypes.DOCTOR: "DR",
    CaregiverTypes.NURSE: "NUR",
    CaregiverTypes.ADMINISTRATIVE_STAFF: "AD",
    CaregiverTypes.PHARMACIST: "PH",
    CaregiverTypes.SURGEON: "SRG",
    CaregiverTypes.PHYSICIAN: "PHY",
    CaregiverTypes.DENTIST: "DNT",
    CaregiverTypes.OPTOMETRIST: "OPT",
    CaregiverTypes.RADIOLOGIST: "RAD",
    CaregiverTypes.PSYCHIATRIST: "PSY",
    CaregiverTypes.PHYSICAL_THERAPIST: "PT",
    CaregiverTypes.OCCUPATIONAL_THERAPIST: "OT",
    CaregiverTypes.MEDICAL_LAB_TECHNICIAN: "MLT",
    CaregiverTypes.PARAMEDIC: "PMD",
    CaregiverTypes.DIETITIAN: "DT",
    CaregiverTypes.SPEECH_THERAPIST: "ST",
    CaregiverTypes.MEDICAL_ASSISTANT: "MA",
    CaregiverTypes.RESPIRATORY_THERAPIST: "RT",
    CaregiverTypes.MIDWIFE: "MW",
    CaregiverTypes.ORTHOPEDIST: "ORTH",
    CaregiverTypes.CARDIOLOGIST: "CARD",
    CaregiverTypes.NEUROLOGIST: "NEU",
    CaregiverTypes.PEDIATRICIAN: "PED",
    CaregiverTypes.DERMATOLOGIST: "DERM",
    CaregiverTypes.GYNECOLOGIST: "GYN",
    CaregiverTypes.UROLOGIST: "URO",
    CaregiverTypes.ONCOLOGIST: "ONC",
    CaregiverTypes.ENDOCRINOLOGIST: "ENDO",
    CaregiverTypes.ANESTHESIOLOGIST: "ANES",
}

