# Generated by Django 5.2.5 on 2025-09-05 16:43

import autoslug.fields
import cloudinary.models
import django.db.models.deletion
import shared.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_deleted_at_organization_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='Caregiver First Name')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Caregiver Last Name')),
                ('caregiver_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Administrative Staff', 'Administrative Staff'), ('Surgeon', 'Surgeon'), ('Physician', 'Physician'), ('Dentist', 'Dentist'), ('Optometrist', 'Optometrist'), ('Radiologist', 'Radiologist'), ('Psychiatrist', 'Psychiatrist'), ('Physical Therapist', 'Physical Therapist'), ('Occupational Therapist', 'Occupational Therapist'), ('Medical Lab Technician', 'Medical Lab Technician'), ('Paramedic', 'Paramedic'), ('Dietitian', 'Dietitian'), ('Speech Therapist', 'Speech Therapist'), ('Medical Assistant', 'Medical Assistant'), ('Respiratory Therapist', 'Respiratory Therapist'), ('Midwife', 'Midwife'), ('Orthopedist', 'Orthopedist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist'), ('Oncologist', 'Oncologist'), ('Endocrinologist', 'Endocrinologist'), ('Anesthesiologist', 'Anesthesiologist')], db_index=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=30, null=True, verbose_name='Caregiver Marital Status')),
                ('profile_picture', cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='image')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[shared.validators.validate_phone_number])),
                ('address', models.TextField(blank=True, null=True, verbose_name="Caregiver's Address")),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='user', unique=True)),
                ('staff_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver',
                'verbose_name_plural': 'Caregivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
