# Generated by Django 5.2.5 on 2025-09-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalrecord',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height of the patient in centimeters (cm)', max_digits=5, null=True),
        ),
    ]
