# Generated by Django 5.2.5 on 2025-09-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientmedicalrecord_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnosisdetails',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='patients.patient', verbose_name='Patient'),
        ),
    ]
