# Generated by Django 5.2.5 on 2025-09-04 09:36

import autoslug.fields
import cloudinary.models
import django.db.models.deletion
import shared.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Organization Name')),
                ('acronym', models.CharField(max_length=15, unique=True, validators=[shared.validators.validate_organization_acronym], verbose_name='Organization Acronym')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, default='default.png', max_length=255, null=True, verbose_name='Organization logo')),
                ('address', models.TextField(blank=True, null=True, verbose_name="Organization's Address")),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[shared.validators.validate_phone_number])),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
